---
  - name: install mariadb
    package:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - mariadb
      - mariadb-server
      - MySQL-python

  - name: install PyMySQL
    pip:
      name: pymysql
      state: present

  - name: restart mariadb
    systemd:
      name: mariadb
      state: restarted
      enabled: yes

  - name: Set root user password
    mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      check_implicit_admin: true

  - name: Add .my.cnf
    template: 
      src: "mariadb/my.cnf.j2" 
      dest: "/root/.my.cnf"
      owner: "root"
      group: "root"
      mode: 0600