---
  - name: install nginx
    package:
      name: nginx
      state: present
      update_cache: yes

  - name: place nginx conf file in place
    template:
      src: "templates/nginx/{{ item.key }}"
      dest: "{{ item.value.dest | default('/etc/nginx/' ~ item.key) }}"
    with_dict:
      nginx.conf:
        dest: /etc/nginx/
      bastion.conf:
        dest: /etc/nginx/conf.d/
    notify:
      - restart nginx
